
{% set version = environ.get('GIT_DESCRIBE_TAG').lstrip('v') %}
{% set number = GIT_DESCRIBE_NUMBER %}

package:
  name: bluebird-pkg
  version: {{ version }}

build:
  number: {{ number }}

about:
  home: https://github.com/gottingen/bluebird
  license: Apache License 2
  license_family: APACHE
  license_file: LICENSE
  summary: library implementing common using data structures for search

source:
  git_url: ../

outputs:
  - name: bluebird
    script: bld.sh   # [not win]
    script: bld.bat  # [win]
    build:
      #   string: "h{{ PKG_HASH }}_{{ number }}"
      run_exports:
        - {{ pin_compatible('bluebird', exact=True) }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - sysroot_linux-64 >=2.17  # [linux64]
        - turbo
      host:
        - sysroot_linux-64 >=2.17  # [linux64]
        - turbo
      run:
        - sysroot_linux-64 >=2.17  # [linux64]
        - turbo
    test:
      commands:
        - test -f $PREFIX/lib/libbits.so              # [linux]
        - test -f $PREFIX/lib/libbits.dylib           # [osx]
      #  - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
      #  - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]
